/** Dynamic Expo config — production vs development (EAS + local). */
const appJson = require("./app.json");

const PROFILE = process.env.EAS_BUILD_PROFILE ?? "development";
const IS_PRODUCTION =
  PROFILE === "production" ||
  process.env.EXPO_PUBLIC_APP_VARIANT === "production";
// Preview APKs install on real phones — default to hosted API, not emulator 10.0.2.2.
const USE_HOSTED_DEFAULTS = IS_PRODUCTION || PROFILE === "preview";

const HOSTED_API =
  appJson.expo.extra?.hostedApiUrl ?? "https://nozywallet.leoninedao.org";

function loadHostedApiKey() {
  const fromEnv = process.env.NOZY_API_KEY?.trim();
  if (fromEnv) return fromEnv;

  try {
    // `hosted-api.env` is gitignored and generated by:
    // `powershell -File scripts\\prepare-mobile-store-credentials.ps1`
    const fs = require("fs");
    const path = require("path");
    const envPath = path.join(__dirname, "hosted-api.env");
    if (!fs.existsSync(envPath)) return null;

    const raw = fs.readFileSync(envPath, "utf8");
    const match = raw.match(/^NOZY_API_KEY=(.+)$/m);
    return match?.[1]?.trim() || null;
  } catch {
    return null;
  }
}

/** @returns {import("@expo/config-types").ExpoConfig} */
module.exports = () => {
  const base = appJson.expo;
  const hostedApiKey = USE_HOSTED_DEFAULTS ? loadHostedApiKey() : null;
  return {
    ...base,
    owner: "leonine-dao",
    extra: {
      ...base.extra,
      appVariant: IS_PRODUCTION ? "production" : "development",
      easBuildProfile: PROFILE,
      enableExperimentalFeatures: !IS_PRODUCTION,
      requireHostedApiKey: USE_HOSTED_DEFAULTS,
      defaultApiUrl: USE_HOSTED_DEFAULTS
        ? HOSTED_API
        : base.extra.defaultApiUrl,
      ...(hostedApiKey ? { hostedApiKey } : {}),
    },
    // Cleartext HTTP is controlled in android/ (debug manifest), not Expo schema —
    // `usesCleartextTraffic` is invalid on android config and is not synced when android/ exists.
    ios: {
      ...base.ios,
      infoPlist: {
        ...base.ios?.infoPlist,
        ITSAppUsesNonExemptEncryption: false,
      },
    },
  };
};
