#!/usr/bin/env bash
# Build and start ironwood-valar lightwalletd in WSL (testnet → Windows zebrad :18232).
set -euo pipefail

TESTNET=0
INSTALL=0
START=0
GRPC_PORT=9067
ZEBRA_RPC_PORT=8232
ZEBRA_RPC_HOST="127.0.0.1"
BRANCH="ironwood-valar"
REPO_URL="https://github.com/zecrocks/lightwalletd.git"

usage() {
  echo "Usage: $0 [--testnet] [--install] [--start] [--grpc-port N] [--zebra-host H] [--zebra-port P]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --testnet) TESTNET=1; shift ;;
    --install) INSTALL=1; shift ;;
    --start) START=1; shift ;;
    --grpc-port) GRPC_PORT="$2"; shift 2 ;;
    --zebra-host) ZEBRA_RPC_HOST="$2"; shift 2 ;;
    --zebra-port) ZEBRA_RPC_PORT="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "Unknown arg: $1"; usage ;;
  esac
done

if [[ "$TESTNET" -eq 1 ]]; then
  [[ "$GRPC_PORT" -eq 9067 ]] && GRPC_PORT=9068
  [[ "$ZEBRA_RPC_PORT" -eq 8232 ]] && ZEBRA_RPC_PORT=18232
  if [[ "$ZEBRA_RPC_HOST" == "127.0.0.1" ]]; then
    ZEBRA_RPC_HOST="$(grep -m1 nameserver /etc/resolv.conf | awk '{print $2}')"
    [[ -z "$ZEBRA_RPC_HOST" ]] && ZEBRA_RPC_HOST="127.0.0.1"
  fi
  REPO="${HOME}/lightwalletd-ironwood-testnet"
  DATA_DIR="${HOME}/.cache/lightwalletd-testnet-ironwood"
  CONF="${HOME}/.config/zcash-testnet.conf"
else
  REPO="${HOME}/lightwalletd-ironwood"
  DATA_DIR="${HOME}/.cache/lightwalletd-ironwood"
  CONF="${HOME}/.config/zcash.conf"
fi

LWD_BIN="${HOME}/go/bin/lightwalletd"
LOG="${DATA_DIR}/lightwalletd.log"
LISTEN="0.0.0.0:${GRPC_PORT}"
HTTP_PORT=$((GRPC_PORT + 1000))

if [[ "$INSTALL" -eq 1 ]]; then
  if ! command -v go >/dev/null 2>&1; then
    echo "MISSING: golang-go — run: sudo apt install -y golang-go protobuf-compiler make git"
    exit 1
  fi
  if [[ ! -d "${REPO}/.git" ]]; then
    git clone --branch "$BRANCH" --single-branch "$REPO_URL" "$REPO"
  else
    cd "$REPO"
    git remote set-url origin "$REPO_URL"
    git fetch origin "$BRANCH"
    git checkout "$BRANCH"
    git pull --ff-only origin "$BRANCH" || true
  fi
  cd "$REPO"
  make
  make install
  test -x "$LWD_BIN"
  echo "Installed: $LWD_BIN ($BRANCH)"
fi

if [[ "$START" -eq 1 ]]; then
  test -x "$LWD_BIN" || { echo "MISSING: run with --install first"; exit 1; }
  mkdir -p "$(dirname "$LOG")" "${DATA_DIR}"
  cat >"$CONF" <<EOF
# lightwalletd -> zebrad (generated by ironwood-lwd-wsl.sh)
rpcuser=zebra
rpcpassword=local
rpcport=${ZEBRA_RPC_PORT}
rpcbind=${ZEBRA_RPC_HOST}
EOF
  if pgrep -f "lightwalletd.*${GRPC_PORT}" >/dev/null; then
    echo "already running on port ${GRPC_PORT}"
    pgrep -a lightwalletd
    exit 0
  fi
  nohup "$LWD_BIN" --grpc-bind-addr "$LISTEN" --http-bind-addr "127.0.0.1:${HTTP_PORT}" \
    --zcash-conf-path "$CONF" --data-dir "$DATA_DIR" --log-file "$LOG" \
    --no-tls-very-insecure >>"$LOG" 2>&1 &
  sleep 5
  pgrep -a lightwalletd || { echo "--- log tail ---"; tail -40 "$LOG"; exit 1; }
  echo "gRPC listening on ${LISTEN} (zebrad ${ZEBRA_RPC_HOST}:${ZEBRA_RPC_PORT})"
fi

if [[ "$INSTALL" -eq 0 && "$START" -eq 0 ]]; then
  usage
fi
