pub mod error;
pub mod hd_wallet;
pub mod notes;
pub mod storage;
pub mod transactions;
pub mod zebra_integration;
pub mod block_parser;
pub mod transaction_builder;
pub mod orchard_tx;
pub mod proving;
pub mod benchmarks;
pub mod rpc_test;
pub mod cli_helpers;
pub mod groth16_prover_simple;
pub mod local_analytics;
pub mod config;
pub mod paths;
pub mod transaction_history;
pub mod transaction_tracker;
pub mod note_sync;
pub mod note_index;
pub mod address_book;
#[cfg(test)]
pub mod tests;

pub use error::{NozyError, NozyResult};
pub use config::BackendKind;
pub use hd_wallet::HDWallet;
pub use notes::{NoteScanner, SpendableNote, NoteScanResult, OrchardNote, SerializableOrchardNote};
pub use storage::{WalletStorage, WalletData};
pub use transactions::{TransactionBuilder, TransactionDetails, SignedTransaction};
pub use zebra_integration::ZebraClient;
pub use block_parser::BlockParser;
pub use transaction_builder::ZcashTransactionBuilder;
pub use rpc_test::RpcTester;
pub use config::{load_config, save_config, update_last_scan_height, WalletConfig};
pub use paths::{get_wallet_data_dir, get_wallet_config_dir, get_wallet_data_path, get_wallet_config_path};
pub use transaction_history::{SentTransactionRecord, TransactionView, TransactionType, TransactionStatus};
pub use transaction_tracker::TransactionConfirmationTracker;
pub use note_sync::{NoteSyncManager, SyncResult};
pub use note_index::NoteIndex;
pub use address_book::{AddressBook, AddressEntry};
pub use cli_helpers::estimate_transaction_fee;
