pub mod error;
pub mod hd_wallet;
pub mod notes;
pub mod storage;
pub mod transactions;
pub mod zebra_integration;
pub mod grpc_client;
pub mod block_parser;
pub mod transaction_builder;
pub mod orchard_tx;
pub mod proving;
pub mod benchmarks;
pub mod rpc_test;
pub mod cli_helpers;
pub mod groth16_prover_simple;
pub mod local_analytics;
pub mod config;
pub mod paths;
pub mod transaction_history;
pub mod transaction_tracker;
pub mod note_sync;
pub mod note_index;
pub mod address_book;
pub mod zeaking_adapter;
pub mod privacy;
pub mod privacy_ui;
pub mod privacy_network;
pub mod monero;
pub mod monero_zk_verifier;
pub mod secret;
pub mod secret_keys;
pub mod swap;
pub mod bridge;
pub mod nu6_1_check;
pub mod progress;
pub mod input_validation;
pub mod cache;
#[cfg(test)]
pub mod tests;

pub use error::{NozyError, NozyResult};
pub use config::{BackendKind, Protocol};
pub use hd_wallet::HDWallet;
pub use notes::{NoteScanner, SpendableNote, NoteScanResult, OrchardNote, SerializableOrchardNote};
pub use storage::{WalletStorage, WalletData};
pub use transactions::{TransactionBuilder, TransactionDetails, SignedTransaction};
pub use zebra_integration::ZebraClient;
pub use block_parser::BlockParser;
pub use transaction_builder::ZcashTransactionBuilder;
pub use rpc_test::RpcTester;
pub use config::{load_config, save_config, update_last_scan_height, WalletConfig};
pub use paths::{get_wallet_data_dir, get_wallet_config_dir, get_wallet_data_path, get_wallet_config_path};
pub use transaction_history::{SentTransactionRecord, TransactionView, TransactionType, TransactionStatus};
pub use transaction_tracker::TransactionConfirmationTracker;
pub use note_sync::{NoteSyncManager, SyncResult};
pub use note_index::NoteIndex;
pub use address_book::{AddressBook, AddressEntry};
pub use cli_helpers::estimate_transaction_fee;
pub use zeaking::{Zeaking, IndexStats, IndexedBlock, IndexedTransaction};
pub use zeaking_adapter::{ZebraBlockSource, ZebraBlockParser};
pub use monero::{MoneroWallet, MoneroRpcClient, MoneroTransactionStorage, MoneroTransactionRecord, MoneroTransactionStatus};
pub use monero_zk_verifier::{MoneroZkVerifier, VerificationLevel, VerificationResult};
pub use secret::{SecretWallet, SecretRpcClient, Snip20Token, SecretTransactionStorage, SecretTransactionRecord, SecretTransactionStatus};
pub use secret_keys::{SecretKeyDerivation, SecretKeyPair, SecretDerivationPath, SECRET_COIN_TYPE, SECRET_ADDRESS_PREFIX};
pub use swap::{SwapService, SwapEngine, SwapDirection, SwapStatus, SwapRequest, SwapResponse};
pub use bridge::{PrivacyValidator, PrivacyCheckResult, ChurnManager, ChurnRecommendation, AddressTracker, SwapStorage, StoredSwap};
